<font color=Purple>
    
# **2.1 Crear arrays multidimensionales.** </font>


In [3]:
import numpy as np

In [4]:
arreglo = np.array([0,1,2,3,4,5])

In [5]:
arreglo, type(arreglo)

(array([0, 1, 2, 3, 4, 5]), numpy.ndarray)

In [11]:
notas = [16,17,18,14,15,19]
arreglo_notas = np.array(notas, dtype=float)
print(arreglo_notas)

[16. 17. 18. 14. 15. 19.]


In [15]:
#array multidimensional
arreglo_notas_todas = np.array((arreglo,notas))
print(arreglo_notas_todas)

[[ 0  1  2  3  4  5]
 [16 17 18 14 15 19]]


### ndim
Nos indica cuántas dimensiones tiene.

In [17]:
print(arreglo_notas_todas.ndim)
print(arreglo.ndim)
print(arreglo_notas.ndim)

2
1
1


### shape
Indica el tamaño de cada dimensión del array.

In [18]:
print(arreglo_notas_todas.shape)
print(arreglo.shape)
print(arreglo_notas.shape)

(2, 6)
(6,)
(6,)


### Arrays especiales
* zeros : Produce un ndarray con todos sus elementos igual a cero.
* ones : Produce un ndarray con todos sus elementos igual a uno.
* identity : Produce una matriz identidad.
* arange : Produce un ndarray cuyos elementos están en el rango especificado.

In [19]:
arr = np.zeros((2,3),dtype=float)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
ar2 = np.ones((3,4), dtype=float)
print(ar2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
ar3 = np.identity((4), dtype=float)
print(ar3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
ar4 = np.arange(1,9)
print(ar4)

[1 2 3 4 5 6 7 8]
