<font color=Purple>
    
# **2.2 Operaciones básicas.** </font>

In [10]:
import numpy as np

arr = np.arange(1,9)
ar2 = np.arange(8,16)

print(arr, ar2)

[1 2 3 4 5 6 7 8] [ 8  9 10 11 12 13 14 15]


In [11]:
arr.shape = (2,4)
print(arr)
ar2.shape = (2,4)
print(ar2)

[[1 2 3 4]
 [5 6 7 8]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [12]:
#Adición
arr + ar2

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [15]:
#Sustracción
ar2 - arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [17]:
#Exponenciación
arr**ar2

array([[         1,        512,      59049,    4194304],
       [ 244140625,  175792128, -381759919,          0]], dtype=int32)

In [19]:
#División
arr/arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])