<font color=Purple>
    
# **2.3 Álgebra lineal.** </font>

### Producto de arrays

In [1]:
import numpy as np

a = np.array([1,2,3], float)
b = np.array([0,1,1], float)

np.dot(b,a)

5.0

In [2]:
a.dot(b)

5.0

### Producto de matrices

In [8]:
a = np.array([[5,2],[4,8]],float)
b = np.array([[1,7],[6,3]],float)

print(a)
print(b)

[[5. 2.]
 [4. 8.]]
[[1. 7.]
 [6. 3.]]


In [9]:
a @ b
#5*1+2*6=17
#5*7+2*3=41
#4*1+8*6=52
#4*7+8*3=52

array([[17., 41.],
       [52., 52.]])

In [10]:
b @ a

array([[33., 58.],
       [42., 36.]])

In [11]:
print(np.matmul(a,b))

[[17. 41.]
 [52. 52.]]


### Determinante de una matriz

In [13]:
a = np.array([[8,5],[3,4]])
print(a)

np.linalg.det(a)

[[8 5]
 [3 4]]


17.0

### Auto-valores y auto-vectores

In [16]:
vals, vecs = np.linalg.eig(a)
print(vals,'\n')
print(vecs)

[10.35889894  1.64110106] 

[[ 0.90440309 -0.61810602]
 [ 0.4266791   0.78609474]]
