#2.6 Agregar y quitar valores a un array

In [1]:
import numpy as np


In [16]:
arr = np.arange(0, 20, 2)
print(" ARRAY CON INICIO EN 0 HASTA 18\n",arr )
arr_flot = np.random.rand(4, 3)
print("\n ARRAY CON 4 FILAS Y 3 COLUMNAS\n",arr_flot)
arr_ent = np.random.randint(10, size=(2,3))
print("\nCREA ARRAY CON VALORES ENTEROS ENTRE 0 Y 9 INCLUSIVE\n",arr_ent)
arr_6 = np.full((3,3), 6)
print("\nMATRIZ DE 3X3, CON 6 COMO VALOR\n",arr_6)
print("\nAPPEND AGREGA VALORES AL FINAL DEL ARRAY\n",np.append(arr, [12, 13, 14, 51]))
print("\nINSERT: AGREGA VALORES EN UNA POSICIÓN ESPECÍFICA\n",np.insert(arr, 2, [42, 34]))
print("\nELIMINA LOS VALORES DEL INDICE EJE 0\n",np.delete(arr_ent, 1, axis=0))

 ARRAY CON INICIO EN 0 HASTA 18
 [ 0  2  4  6  8 10 12 14 16 18]

 ARRAY CON 4 FILAS Y 3 COLUMNAS
 [[0.53655988 0.07789398 0.59301994]
 [0.26420223 0.13943436 0.42302649]
 [0.1213422  0.02128686 0.06365179]
 [0.707805   0.04287707 0.78601311]]

CREA ARRAY CON VALORES ENTEROS ENTRE 0 Y 9 INCLUSIVE
 [[2 7 9]
 [5 6 2]]

MATRIZ DE 3X3, CON 6 COMO VALOR
 [[6 6 6]
 [6 6 6]
 [6 6 6]]

APPEND AGREGA VALORES AL FINAL DEL ARRAY
 [ 0  2  4  6  8 10 12 14 16 18 12 13 14 51]

INSERT: AGREGA VALORES EN UNA POSICIÓN ESPECÍFICA
 [ 0  2 42 34  4  6  8 10 12 14 16 18]

ELIMINA LOS VALORES DEL INDICE EJE 0
 [[2 7 9]]
