#2.7 Transformaciones

In [1]:
import numpy as np

## As Type
Este método nos permite modificar el tipo de dato de los valores de un array.

In [10]:
arr_ent = np.random.randint(100, size = (3, 4))
print("ARRAY CON NÚMEROS ENTEROS\n",arr_ent)
print("\nMISMO ARRAY CON NÚMEROS FLOTANTES\n",arr_ent.astype(float))

ARRAY CON NÚMEROS ENTEROS
 [[70 50 69 28]
 [86 14 73 76]
 [77 17 93 87]]

MISMO ARRAY CON NÚMEROS FLOTANTES
 [[70. 50. 69. 28.]
 [86. 14. 73. 76.]
 [77. 17. 93. 87.]]


#Sort

Este método nos permite ordenar los valores de un array.

In [39]:
arr_ent = np.random.randint(100, size = (3, 4))
print("ARRAY ORIGINAL\n",arr_ent)
arr_ent.sort()
print("\nARRAY ORDENADO FILA X FILA\n",arr_ent)
arr_ent.sort(axis = 0)
print("\nARRAY ORDENADO COLUMNA X COLUMNA\n",arr_ent)

ARRAY ORIGINAL
 [[16 82 63 49]
 [78 16 42  2]
 [29 58 87 12]]

ARRAY ORDENADO FILA X FILA
 [[16 49 63 82]
 [ 2 16 42 78]
 [12 29 58 87]]

ARRAY ORDENADO COLUMNA X COLUMNA
 [[ 2 16 42 78]
 [12 29 58 82]
 [16 49 63 87]]


#Reshape

Este método nos permite modificar las dimensiones de un array.

In [17]:
arr_ent = arr_ent.reshape(4, 3) 
print(arr_ent)

[[ 3 19 45]
 [59  9 36]
 [50 73 22]
 [42 66 93]]


#Flatten

Este método crea un array unidimensional desde el original.

In [21]:
plano_arr = arr_ent.flatten()
print(" ARRAY UNIDIMENSIONAL\n",plano_arr)

 ARRAY UNIDIMENSIONAL
 [ 3 19 45 59  9 36 50 73 22 42 66 93]


#To List

Este método crea una lista a partir de un array.

In [24]:
lista_arr = plano_arr.tolist()
print(" LISTA A PARTIR DE UN ARRAY\n",lista_arr)

 LISTA A PARTIR DE UN ARRAY
 [3, 19, 45, 59, 9, 36, 50, 73, 22, 42, 66, 93]


#Separar y juntar arrays


In [32]:
arrays = np.split(arr_ent, 4)
print("ARRAY ORIGINAL\n",arr_ent)
print("\nSEPARA EL ARRAY ANTERIOR EN ARRAYS SEPARADOS\n",arrays)

print("\nCONCATENA LOS ARRAYS SEPARADOS DE POSICIÓN 1 CON EL DE POSICIÓN 0\n",np.concatenate((arrays[1], arrays[0]), axis = 0))

ARRAY ORIGINAL
 [[ 3 19 45]
 [59  9 36]
 [50 73 22]
 [42 66 93]]

SEPARA EL ARRAY ANTERIOR EN ARRAYS SEPARADOS
 [array([[ 3, 19, 45]]), array([[59,  9, 36]]), array([[50, 73, 22]]), array([[42, 66, 93]])]

CONCATENA LOS ARRAYS SEPARADOS DE POSICIÓN 1 CON EL DE POSICIÓN 0
 [[59  9 36]
 [ 3 19 45]]
