#2.8 Indexación y slicing

In [1]:
import numpy as np

In [3]:
#CREO UN ARRAY

arr = np.array(range(64)).reshape((8,8))
print("ARRAY ORIGINAL\n",arr)

ARRAY ORIGINAL
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [15]:
#SELECCIONO DE LA FILA 1 EL ELEMENTO 2
print("ARRAY ORIGINAL\n",arr)
print("\narr[1, 2] = ",arr[1, 2]) #10

ARRAY ORIGINAL
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]

arr[1, 2] =  10


In [18]:
#SELECCIONO DESDE LAS FILAS 0 A 6, LAS FILAS DE 2 EN 2
print("arr[0: 7: 2,] ES: \n", arr[0: 7: 2,])


arr[0: 7: 2,] ES: 
 [[ 0  1  2  3  4  5  6  7]
 [16 17 18 19 20 21 22 23]
 [32 33 34 35 36 37 38 39]
 [48 49 50 51 52 53 54 55]]


In [19]:
#DE LA FILA 1, TOMA LOS ELEMENTOS DEL 3 HASTA EL FINAL
print("arr[1, 3:] ES \n",arr[1, 3:])

arr[1, 3:] ES  [11 12 13 14 15]


In [21]:
#DE LAS FILAS 1, 3 Y 5, LOS ELEMENTOS DE LAS POSICIONES 3, 6 Y 7
print("arr[ [1, 3, 5], [3, 6, 7]] ES \n",arr[ [1, 3, 5], [3, 6, 7]])

arr[ [1, 3, 5], [3, 6, 7]] ES 
 [11 30 47]


In [20]:
#DE LAS FILAS 1, 3 Y 5, TRAE TODOS LOS ELEMENTOS DE 3 EN 3
print("arr[ [1, 3, 5], ::3] ES \n",arr[ [1, 3, 5], ::3])

arr[ [1, 3, 5], ::3] ES 
 [[ 8 11 14]
 [24 27 30]
 [40 43 46]]


#Indexación booleana

In [23]:
#CREO UN ARRAY
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
#QUIERO SABER CON TRUE O FALSE QUE VALORES SON MENORES A 4
data < 4

array([ True,  True,  True,  True, False, False, False, False])

In [25]:
#QUE VALORES SON LOS MENORES A 4
data[data < 4]

array([0, 1, 2, 3])

In [27]:
#QUE VALORES SON LOS MENORES A 4
data[np.array([ True,  True,  True,  True, False, False, False, False])]

array([0, 1, 2, 3])

In [28]:
#CREO UN ARRAY
amigos = np.array(['giulia', 'marina', 'pablo', 'eliana'])

In [30]:
  #EL NOMBRE ELIANA ESTA EN EL ARRAY AMIGOS
'eliana' in amigos

True

In [31]:
#TODOS LOS AMIGOS QUE NO SEAN MARINA
amigos[amigos!= 'marina']

array(['giulia', 'pablo', 'eliana'], dtype='<U6')